### ISSUE TITLE
Fix for netspeed at speedtest.py Line 772

### ISSUE THREAD

**Issue by nunigaia** [oe-alliance/3rdparty-plugins-python3#4]
Instead of:

        if shutdown_event.isSet():

Should be:

        if shutdown_event.is_set():

-----------------------------------

**Comment by AbuBaniaz** [comment]
For which plugin is this? Do you have the modified/updated ipk please?

**Comment by nunigaia** [comment]
> For which plugin is this? Do you have the modified/updated ipk please?

Plugin name: netspeedtest

Fix for 3.11 ( python code based images )

Yes ... ScreenShot issue:

![imagem](https://user-images.githubusercontent.com/12786802/219026589-1a5390a8-0d02-43f0-ade7-3ae457d018cd.png)

File:

[enigma2-plugin-extensions-netspeedtest_2.1.3_all.ipk.zip](https://github.com/oe-alliance/3rdparty-plugins-python3/files/10742903/enigma2-plugin-extensions-netspeedtest_2.1.3_all.ipk.zip)

If you need that i bump the version to 2.1.4 i will do it.

**Comment by AbuBaniaz** [comment]
If he plugin we have is faulty and you now have a fixed one, we should replace the faulty one and use the working one. Can you please supply the working one with an increased version number.

**Comment by nunigaia** [comment]
Ok,

Here it is the working version, bumped to 2.1.4

[enigma2-plugin-extensions-netspeedtest_2.1.4_all.ipk.zip](https://github.com/oe-alliance/3rdparty-plugins-python3/files/10745400/enigma2-plugin-extensions-netspeedtest_2.1.4_all.ipk.zip)

thanks
nunigaia

**Comment by mike-99** [comment]
Thx, Done [update netspeedtest_2.1.4](https://github.com/oe-alliance/3rdparty-plugins-python3/commit/4b6240e9e48c72d0f902c3db793e17858bf94883)
